### PR TITLE
Prevent exception on TopicRank when there are no noun_chunks

### PR DESCRIPTION
**Pull request by tomaarsen**
Hello!

## Pull request overview
* Added a simple return case to the TopicRank `_cluster` method, to prevent an exception when there are no candidates (i.e. no noun chunks).
* Added a test to verify that this works now.

### Test 1 - Language without noun_chunks
<details>
<summary>Input</summary>

```python
from icecream import ic
import spacy
import pytextrank

# example text
text = """Цены фьючерсов на газ в Европе в понедельник выросли более чем вполовину, превысив 3500 долларов за тысячу кубометров, свидетельствуют данные лондонской биржи ICE.
Торги открылись с 2366,8 долларов за тысячу кубометров, но котировки сразу же пошли вверх. За час они подскочили почти на тысячу долларов. При этом расчетная цена на пятницу составляла 2170,2 доллара.
Европейский газовый рынок лихорадит уже много месяцев. Весной прошлого года цены колебались на уровне 250-300 долларов за тысячу кубов, к концу августа они выросли до 600 долларов, в октябре впервые перевалили за тысячу, а в декабре — за две тысячи. Затем последовал некоторый откат, но цены оставались стабильно высокими, чего не наблюдалось за всю историю функционирования газовых хабов в Европе."""

# load a spaCy model, depending on language, scale, etc.
nlp = spacy.load("ru_core_news_lg")

ic("topicrank")
nlp.add_pipe("topicrank")

doc = nlp(text)

ic(doc._.phrases)
for phrase in doc._.phrases:
    ic(phrase.text)
    ic(phrase.rank, phrase.count)
    ic(phrase.chunks)
```
</details>
<details>
<summary>Output of main branch</summary>

```python
ic| 'topicrank'
Traceback (most recent call last):
  File "c:\GitHub\pytextrank\ptr_204.py", line 16, in <module>
    doc = nlp(text)
  File "C:\GitHub\pytextrank\.env39\lib\site-packages\spacy\language.py", line 1019, in __call__
    error_handler(name, proc, [doc], e)
  File "C:\GitHub\pytextrank\.env39\lib\site-packages\spacy\util.py", line 1618, in raise_error
    raise e
  File "C:\GitHub\pytextrank\.env39\lib\site-packages\spacy\language.py", line 1014, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
  File "c:\GitHub\pytextrank\pytextrank\topicrank.py", line 87, in __call__
    doc._.phrases = doc._.textrank.calc_textrank()
  File "c:\GitHub\pytextrank\pytextrank\topicrank.py", line 333, in calc_textrank
    self.lemma_graph = self._construct_graph()
  File "c:\GitHub\pytextrank\pytextrank\base.py", line 414, in _construct_graph
    g.add_nodes_from(self.node_list)
  File "c:\GitHub\pytextrank\pytextrank\topicrank.py", line 280, in node_list
    clustered = [tuple(cluster) for cluster in self._cluster(candidates)]
  File "c:\GitHub\pytextrank\pytextrank\topicrank.py", line 211, in _cluster
    pairwise_dist = pdist(matrix, "jaccard")
  File "C:\GitHub\pytextrank\.env39\lib\site-packages\scipy\spatial\distance.py", line 2231, in pdist
    raise ValueError('A 2-dimensional array must be passed.')
ValueError: A 2-dimensional array must be passed.
```
</details>
<details>
<summary>Output of this PR</summary>

```python
ic| 'topicrank'
ic| doc._.phrases: []
```
</details>

### Test 2 - Empty document
<details>
<summary>Input</summary>

```python
from icecream import ic
import spacy
import pytextrank

# example text
text = ""

# load a spaCy model, depending on language, scale, etc.
nlp = spacy.load("ru_core_news_lg")

ic("topicrank")
nlp.add_pipe("topicrank")

doc = nlp(text)

ic(doc._.phrases)
for phrase in doc._.phrases:
    ic(phrase.text)
    ic(phrase.rank, phrase.count)
    ic(phrase.chunks)
```
</details>
<details>
<summary>Output of main branch</summary>

```python
ic| 'topicrank'
Traceback (most recent call last):
  File "c:\GitHub\pytextrank\ptr_204.py", line 14, in <module>
    doc = nlp(text)
  File "C:\GitHub\pytextrank\.env39\lib\site-packages\spacy\language.py", line 1019, in __call__     
    error_handler(name, proc, [doc], e)
  File "C:\GitHub\pytextrank\.env39\lib\site-packages\spacy\util.py", line 1618, in raise_error      
    raise e
  File "C:\GitHub\pytextrank\.env39\lib\site-packages\spacy\language.py", line 1014, in __call__     
    doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
  File "c:\GitHub\pytextrank\pytextrank\topicrank.py", line 87, in __call__
    doc._.phrases = doc._.textrank.calc_textrank()
  File "c:\GitHub\pytextrank\pytextrank\topicrank.py", line 333, in calc_textrank
    self.lemma_graph = self._construct_graph()
  File "c:\GitHub\pytextrank\pytextrank\base.py", line 414, in _construct_graph
    g.add_nodes_from(self.node_list)
  File "c:\GitHub\pytextrank\pytextrank\topicrank.py", line 280, in node_list
    clustered = [tuple(cluster) for cluster in self._cluster(candidates)]
  File "c:\GitHub\pytextrank\pytextrank\topicrank.py", line 211, in _cluster
    pairwise_dist = pdist(matrix, "jaccard")
  File "C:\GitHub\pytextrank\.env39\lib\site-packages\scipy\spatial\distance.py", line 2231, in pdist
    raise ValueError('A 2-dimensional array must be passed.')
ValueError: A 2-dimensional array must be passed.
```
</details>
<details>
<summary>Output of this PR</summary>

```python
ic| 'topicrank'
ic| doc._.phrases: []
```
</details>
This case is added as a test.

## Background on the bug
Previously, if `candidates` was empty, then `matrix` would be empty in the following snippet, and `pdist` would throw an exception, as `matrix` ought to be a 2-dimensional list. 
https://github.com/DerwenAI/pytextrank/blob/9ab64507a26f946191504598f86021f511245cd7/pytextrank/topicrank.py#L193-L211
This can easily be resolved by checking if `candidates` is empty, and returning an empty list if so. It is very sensible that if there are no candidates, then the list of clusters for the candidates is empty too. 

## Note
I only now caught up to the discussion in #204, which showed me that this issue still existed. Apologies for being a bit late with this. Note that the snippet from https://github.com/DerwenAI/pytextrank/issues/204#issuecomment-1061049290 produces an empty set of phrases for TopicRank, while the other algorithms do produce phrases. This is because TopicRank only considers noun_chunks, and not entities, while the other TextRank algorithms consider both, as can be seen in this snippet:
https://github.com/DerwenAI/pytextrank/blob/9ab64507a26f946191504598f86021f511245cd7/pytextrank/base.py#L362-L371

It should in theory be possible (I believe) to also add entities to TopicRank, by simply modifying the following snippet to also add `self.doc.ents` to the candidates:
https://github.com/DerwenAI/pytextrank/blob/9ab64507a26f946191504598f86021f511245cd7/pytextrank/topicrank.py#L231-L258

- Tom Aarsen

### CODE REVIEW

**Comment by tomaarsen** [comment]
It seems that the new spaCy v3.3 (and the corresponding model) has caused 2 of our `summary` tests to break. There is something to be said for attempting to fix the spacy version, but it is also important to "keep up" with spaCy updates. I'll just update the tests according to the new spaCy version.

**Comment by tomaarsen** [comment]
Please note that this spaCy v3.3 test issue is also the reason that #217 is failing. The changes introduced in that PR, as well as the test from that PR, both do seem to pass the tests.

**Comment by ceteri** [comment]
Outstanding! This looks wonderful @tomaarsen 

I've been wondering whether we should try to have a collection of test results, one per range of `spaCy` release numbers? That way when there are updates which make subtle changes in the ranked phrases results, we could have test coverage that is more adaptable?

**Comment by ceteri** [comment]
Hi @tomaarsen ,
The CI environment which GitHub uses produces different results, <https://github.com/DerwenAI/pytextrank/runs/7505758231?check_suite_focus=true>

I'll need to dig in more to find out why :)

**Comment by tomaarsen** [comment]
I've selected two small snippets from the current CI logs, in the pip dependency install section:
```
Collecting spacy>=3.0
  Downloading spacy-3.4.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.3 MB)
```
```
Successfully installed en-core-web-sm-3.4.0
```

While my commit 2ffc0048b728be87a8cb40843530ee10a6ebce46 was made for `spaCy 3.3.1 and en-core-web-sm 3.3.0`.
This is once again an issue of a test suite that only works for a specific spaCy version, but that installs the most recent version regardless.

**Pull request merged**
