### PR TITLE
Remove deprecated arg

### PR DESCRIPTION
**Pull request by laxatives**

### CODE REVIEW

**Comment by jakubvalenta** [comment]
I can confirm that this PR fixes issue #15. `parse_doc()` succeeds now. I think this can be merged, @ceteri.

**Comment by clayms** [comment]
should also include https://github.com/ceteri/pytextrank/issues/18#issuecomment-390398883 ?

**Comment by red1** [comment]
Can Someone please approve and Merge ?

**Comment by nicostuhlfauth** [comment]
Works pretty well! Can you please merge this PR? Non-English Spacy modules require version >= 2.0...

**Comment by NirmalVatsyayan** [comment]
Is this solution merged ? The master doesn't seems compatible to latest Spacy version.

**Comment by ThunderHeavyIndustries** [comment]
Just ran in to this problem, duplicated this PR and it does fix the issue. Would be nice if it were merged.

**Pull request merged**
